# Generated by Django 5.2.5 on 2025-08-20 01:24

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=150)),
                ('category_name', models.CharField(max_length=100)),
                ('view_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Blog Post Summary',
                'verbose_name_plural': 'Blog Post Summaries',
                'db_table': 'blog_post_summary_view',
                'ordering': ['-view_count'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GISEnabledModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GIS Enabled Model',
                'verbose_name_plural': 'GIS Enabled Models',
                'required_db_features': ['gis_enabled'],
            },
        ),
        migrations.CreateModel(
            name='PostgreSQLSpecificModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'PostgreSQL Specific Model',
                'verbose_name_plural': 'PostgreSQL Specific Models',
                'required_db_vendor': 'postgresql',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'custom_blog_posts',
                'db_table_comment': 'Blog posts with custom table name and comprehensive meta options',
                'ordering': ['-created', 'title'],
                'permissions': [('can_publish_post', 'Can publish blog posts'), ('can_feature_post', 'Can feature blog posts'), ('can_moderate_post', 'Can moderate blog posts')],
            },
        ),
        migrations.CreateModel(
            name='PublishedBlogPost',
            fields=[
            ],
            options={
                'verbose_name': 'Published Blog Post',
                'verbose_name_plural': 'Published Blog Posts',
                'ordering': ['-views_count', '-created'],
                'permissions': [('can_view_analytics', 'Can view blog post analytics')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meta_practice.blogpost',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='meta_practice.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
                'default_related_name': 'categories_%(class)s',
            },
        ),
        migrations.CreateModel(
            name='ConfigurableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configurable Model',
                'verbose_name_plural': 'Configurable Models',
                'ordering': ['-priority', 'name'],
                'select_on_save': False,
                'base_manager_name': 'custom',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['priority', 'is_active'], name='meta_practi_priorit_5e39a4_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LegacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Legacy Model',
                'verbose_name_plural': 'Legacy Models',
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_practice.category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_practice.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-usage_count', 'name'],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['-usage_count'], name='meta_practi_usage_c_cc90d6_idx'), models.Index(fields=['name'], name='meta_practi_name_770e19_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_practice.category')),
                ('tags', models.ManyToManyField(blank=True, to='meta_practice.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category__name', 'name'],
                'permissions': [('can_manage_inventory', 'Can manage product inventory'), ('can_set_prices', 'Can set product prices'), ('can_activate_products', 'Can activate/deactivate products')],
                'get_latest_by': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='CompleteExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_practice.category')),
                ('tags', models.ManyToManyField(blank=True, to='meta_practice.tag')),
            ],
            options={
                'verbose_name': 'Complete Example',
                'verbose_name_plural': 'Complete Examples',
                'db_table': 'complete_example',
                'db_table_comment': 'Complete example demonstrating all Meta options',
                'ordering': ['-is_featured', '-priority', '-created'],
                'permissions': [('can_feature', 'Can feature items'), ('can_set_priority', 'Can set priority')],
                'get_latest_by': ['-created', '-modified'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='custom_blog_slug_27651a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', '-created'], name='custom_blog_author__9b4a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published', '-views_count'], name='custom_blog_publish_582881_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created'], name='blogpost_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.CheckConstraint(condition=models.Q(('views_count__gte', 0)), name='meta_positive_views_count'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('author', 'slug'), name='meta_unique_author_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='meta_unique_category_name_per_parent'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('votes__gte', -100), ('votes__lte', 100)), name='meta_answer_votes_range'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='meta_practi_categor_c98006_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', '-created'], name='meta_practi_price_132196_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['name'], name='active_product_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='meta_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='meta_positive_stock'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='meta_unique_product_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='completeexamplemodel',
            index=models.Index(fields=['category', 'is_active'], name='complete_ex_categor_a30d09_idx'),
        ),
        migrations.AddIndex(
            model_name='completeexamplemodel',
            index=models.Index(fields=['-priority', '-created'], name='complete_ex_priorit_d0b882_idx'),
        ),
        migrations.AddIndex(
            model_name='completeexamplemodel',
            index=models.Index(fields=['is_featured', '-view_count'], name='complete_ex_is_feat_d7c7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='completeexamplemodel',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['title'], name='active_complete_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='completeexamplemodel',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 0), ('priority__lte', 10)), name='meta_priority_range_0_to_10'),
        ),
        migrations.AddConstraint(
            model_name='completeexamplemodel',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='meta_positive_view_count'),
        ),
        migrations.AddConstraint(
            model_name='completeexamplemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('title', 'category'), name='meta_unique_active_title_per_category'),
        ),
    ]
