# Generated by Django 5.2.5 on 2025-08-20 00:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedFieldExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('integer_field', models.IntegerField(default=0)),
                ('big_integer', models.BigIntegerField(default=0)),
                ('small_integer', models.SmallIntegerField(default=0)),
                ('positive_integer', models.PositiveIntegerField(default=0)),
                ('positive_small_integer', models.PositiveSmallIntegerField(default=0)),
                ('float_field', models.FloatField(default=0.0)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_field', models.DateField(auto_now_add=True)),
                ('datetime_field', models.DateTimeField(auto_now=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('duration_field', models.DurationField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, default=dict)),
                ('binary_data', models.BinaryField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('score', models.IntegerField(default=0, help_text='Score between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Advanced Field Example',
                'verbose_name_plural': 'Advanced Field Examples',
                'ordering': ['-datetime_field'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publication_date', models.DateField()),
                ('pages', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_published', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='books', to='blog.author')),
            ],
            options={
                'ordering': ['-publication_date'],
                'unique_together': {('title', 'publication_date')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(db_column='product_sku', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, db_comment='Internal notes about the product')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'is_available'], name='blog_produc_name_c95e81_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_price')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.book')),
            ],
            options={
                'unique_together': {('book', 'reviewer_name')},
            },
        ),
    ]
