# Generated by Django 5.2.5 on 2025-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_advancedfieldexample_author_book_product_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'migration_practice',
                'ordering': ['-created_at'],
            },
        ),
    ]
