# Generated by Django 5.2.5 on 2025-08-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_practice_model'),
    ]

    operations = [
    ]
