# Generated by Django 5.2.5 on 2025-08-19 18:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import myapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_blog_place_studentinherited_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOC', 'Word Document'), ('XLS', 'Excel File'), ('IMG', 'Image File')], default='PDF', max_length=3)),
                ('file', models.FileField(max_length=500, upload_to=myapp.models.Document.user_directory_path)),
                ('thumbnail', models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to='thumbnails/', width_field='thumbnail_width')),
                ('thumbnail_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('thumbnail_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('template_path', models.FilePathField(blank=True, match='.*\\.html$', null=True, path='/templates/', recursive=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Tên sản phẩm', max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_sold', models.BigIntegerField(default=0)),
                ('rating_count', models.PositiveBigIntegerField(default=0)),
                ('category_priority', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('daily_update_time', models.TimeField(blank=True, null=True)),
                ('warranty_period', models.DurationField(blank=True, help_text='Thời gian bảo hành', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('custom_data', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('client_ip', models.GenericIPAddressField()),
                ('server_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(db_comment='Log message content')),
                ('status_code', models.IntegerField(default=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('daily_sequence', models.CharField(max_length=10, unique_for_date='log_date')),
            ],
            options={
                'verbose_name': 'Server Log',
                'verbose_name_plural': 'Server Logs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, error_messages={'max_length': 'Số điện thoại không được vượt quá 15 ký tự.'}, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[myapp.models.validate_birth_date])),
                ('country', models.CharField(choices=myapp.models.UserProfile.get_country_choices, default='VN', max_length=2)),
                ('preferences', models.JSONField(default=myapp.models.UserProfile.default_preferences)),
                ('membership_code', models.CharField(blank=True, max_length=10, null=True, unique_for_year='date_joined')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique_for_date='published_date')),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('authors', models.ManyToManyField(limit_choices_to={'birth_date__year__gte': 1980}, related_name='articles', to='myapp.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('PR', 'Processing'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('CN', 'Cancelled')], default='PD', max_length=2)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='myapp.person')),
            ],
            options={
                'ordering': ['-order_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='myapp.OrderItem', to='myapp.product'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='myapp.person')),
            ],
            options={
                'db_table': 'custom_blog_posts',
                'permissions': [('can_publish', 'Can publish blog posts')],
                'indexes': [models.Index(fields=['title', 'is_published'], name='custom_blog_title_3c18b5_idx'), models.Index(fields=['-created_at'], name='custom_blog_created_9bcbff_idx')],
            },
        ),
    ]
