# Generated by Django 5.2.5 on 2025-08-19 18:20

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_document_product_serverlog_userprofile_article_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedIndexDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Advanced Index Demo',
                'verbose_name_plural': 'Advanced Index Demos',
                'ordering': ['-created_at', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='FullTextSearchDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('location_data', models.JSONField(default=dict)),
                ('search_title', models.TextField(blank=True)),
                ('search_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=500)),
                ('search_vector', models.TextField(blank=True)),
                ('primary_category', models.CharField(max_length=100)),
                ('secondary_category', models.CharField(blank=True, max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('featured', 'Featured')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_title_published_idx',
            old_name='custom_blog_title_3c18b5_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_created_desc_idx',
            old_name='custom_blog_created_9bcbff_idx',
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='blog_lower_title_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['author'], name='blog_published_author_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['-created_at'], name='blog_published_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='blog_title_search_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_number_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='order_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='order_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-order_date'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-order_date'], name='order_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['PD', 'PR'])), fields=['priority'], name='active_order_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-total_amount'], name='order_amount_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='product_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['price'], name='active_product_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='product_lower_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_priority', '-price'], name='product_priority_price_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['client_ip'], name='serverlog_client_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['status_code'], name='serverlog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['-timestamp'], name='serverlog_timestamp_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['log_date', 'daily_sequence'], name='serverlog_daily_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(fields=['status_code', '-timestamp'], name='serverlog_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='serverlog',
            index=models.Index(condition=models.Q(('status_code__gte', 400)), fields=['timestamp'], name='serverlog_errors_idx'),
        ),
        migrations.AddField(
            model_name='advancedindexdemo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_items', to='myapp.person'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['title'], name='fts_title_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['language'], name='fts_language_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='fts_title_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(django.db.models.functions.text.Length('content'), name='fts_content_length_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['keywords'], name='fts_keywords_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['categories'], name='fts_categories_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['location_data'], name='fts_location_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['title', 'language'], name='fts_title_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['search_title'], name='fts_search_title_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['search_content'], name='fts_search_content_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['-created_at'], name='fts_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(fields=['language', '-created_at'], name='fts_lang_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(condition=models.Q(('language', 'en')), fields=['title'], name='fts_english_title_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(condition=models.Q(('language', 'vi')), fields=['title'], name='fts_vietnamese_title_idx'),
        ),
        migrations.AddIndex(
            model_name='fulltextsearchdemo',
            index=models.Index(condition=models.Q(('content__isnull', False)), fields=['language', 'title'], name='fts_lang_title_content_idx'),
        ),
        migrations.AddField(
            model_name='searchablecontent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['title'], name='demo_title_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['category'], name='demo_category_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['slug'], name='demo_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['-created_at'], name='demo_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['-views'], name='demo_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['-rating'], name='demo_rating_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['category', 'is_active'], name='demo_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['author', '-created_at'], name='demo_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['is_featured', 'is_active', '-rating'], name='demo_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['category', '-published_date', 'title'], name='demo_cat_pub_title_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['-rating', 'price'], name='demo_rating_price_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='demo_lower_title_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.functions.text.Upper('category'), name='demo_upper_category_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('rating')), name='demo_price_rating_calc_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.functions.math.Round('rating'), name='demo_rating_rounded_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['title'], name='demo_active_title_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_premium', True)), fields=['price'], name='demo_premium_price_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_featured', True)), fields=['-created_at'], name='demo_featured_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('rating__gte', 4.0)), fields=['rating'], name='demo_high_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_active', True), ('is_featured', True)), fields=['views'], name='demo_active_featured_views_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_active', True), ('published_date__isnull', False)), fields=['category', 'price'], name='demo_active_published_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('is_premium', True), ('is_featured', True), _connector='OR'), fields=['-created_at'], name='demo_special_items_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('published_date__year', 2024)), fields=['title'], name='demo_2024_title_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(condition=models.Q(('created_at__gte', datetime.datetime(2024, 1, 1, 0, 0))), fields=['author'], name='demo_recent_author_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['category'], include=('title', 'price'), name='demo_covering_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(fields=['author'], include=('title', 'rating', 'views'), name='demo_author_covering_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Upper('category'), name='demo_title_cat_funcs_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedindexdemo',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('views'), '+', models.F('rating')), django.db.models.expressions.CombinedExpression(models.F('price'), '/', models.Value(100)), name='demo_calc_expressions_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['search_vector'], name='search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['title'], name='search_title_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='search_title_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['primary_category', 'status'], name='search_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['primary_category', '-published_at'], name='search_cat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('secondary_category__gt', '')), fields=['secondary_category'], name='search_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['-view_count'], name='search_popular_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['-like_count'], name='search_liked_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('view_count'), '+', django.db.models.expressions.CombinedExpression(models.F('like_count'), '*', models.Value(2))), name='search_engagement_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['status', '-published_at'], name='search_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['-published_at'], name='search_published_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('status', 'featured')), fields=['-featured_until'], name='search_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['author', '-published_at'], name='search_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['author'], name='search_author_published_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('published_at__isnull', False), ('status', 'published')), fields=['primary_category', '-view_count'], name='search_cat_popular_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(condition=models.Q(('status__in', ['published', 'featured'])), fields=['-published_at'], name='search_public_recent_idx'),
        ),
    ]
