# Generated by Django 5.2.5 on 2025-08-19 18:21

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_advancedindexdemo_fulltextsearchdemo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueIndexDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=100)),
                ('tenant_id', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='unique_name_idx'), models.Index(fields=['email'], name='unique_email_idx'), models.Index(fields=['slug'], name='unique_slug_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['email'], name='unique_active_email_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['name', 'tenant_id'], name='unique_tenant_name_idx'), models.Index(fields=['slug', 'tenant_id'], name='unique_tenant_slug_idx'), models.Index(condition=models.Q(('status', 'active')), fields=['email'], name='unique_active_user_email_idx'), models.Index(condition=models.Q(('status__in', ['active', 'pending'])), fields=['name'], name='unique_live_user_name_idx'), models.Index(fields=['tenant_id', '-created_at'], name='unique_tenant_created_idx'), models.Index(fields=['status', 'tenant_id'], name='unique_status_tenant_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['-created_at'], name='unique_active_recent_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email', 'tenant_id'), name='unique_active_email_per_tenant'), models.UniqueConstraint(fields=('slug', 'tenant_id'), name='unique_slug_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceOptimizedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('main_category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('quality_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('engagement_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_content', to='myapp.person')),
            ],
            options={
                'ordering': ['-published_at', '-popularity_score'],
                'indexes': [models.Index(fields=['uuid'], name='perf_uuid_idx'), models.Index(fields=['external_id'], name='perf_external_id_idx'), models.Index(fields=['main_category'], name='perf_main_cat_idx'), models.Index(fields=['main_category', 'sub_category'], name='perf_cat_subcat_idx'), models.Index(condition=models.Q(('sub_category__gt', '')), fields=['sub_category'], name='perf_subcat_idx'), models.Index(condition=models.Q(('is_published', True)), fields=['main_category', '-published_at'], name='perf_published_cat_date_idx'), models.Index(condition=models.Q(('is_featured', True), ('is_published', True)), fields=['main_category', '-published_at'], name='perf_featured_cat_date_idx'), models.Index(condition=models.Q(('is_published', True)), fields=['main_category', '-popularity_score'], name='perf_cat_popularity_idx'), models.Index(condition=models.Q(('is_published', True)), fields=['-quality_rating'], name='perf_quality_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('popularity_score'), '+', models.F('quality_rating')), name='perf_combined_score_idx'), models.Index(condition=models.Q(('is_published', True)), fields=['-published_at'], name='perf_recent_published_idx'), models.Index(condition=models.Q(('is_published', True), ('is_trending', True)), fields=['-published_at'], name='perf_trending_idx'), models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='perf_expiring_idx'), models.Index(condition=models.Q(('is_premium', True), ('is_published', True)), fields=['main_category', '-published_at'], name='perf_premium_cat_idx'), models.Index(fields=['owner', '-published_at'], name='perf_author_date_idx'), models.Index(condition=models.Q(('is_published', True)), fields=['owner'], name='perf_author_published_idx'), models.Index(fields=['title'], name='perf_title_search_idx'), models.Index(django.db.models.functions.text.Lower('title'), name='perf_title_lower_idx'), models.Index(fields=['main_category', 'title'], name='perf_cat_title_idx'), models.Index(fields=['is_published', '-last_modified'], name='perf_status_modified_idx'), models.Index(condition=models.Q(('is_published', False)), fields=['-last_modified'], name='perf_draft_modified_idx'), models.Index(fields=['tags'], name='perf_tags_idx'), models.Index(fields=['main_category'], include=('title', 'published_at', 'popularity_score'), name='perf_cat_covering_idx'), models.Index(fields=['owner'], include=('title', 'main_category', 'published_at'), name='perf_author_covering_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quality_rating__gte', 0), ('quality_rating__lte', 5)), name='perf_valid_quality_rating'), models.CheckConstraint(condition=models.Q(('popularity_score__gte', 0)), name='perf_valid_popularity_score')],
            },
        ),
    ]
