# Generated by Django 5.2.5 on 2025-08-19 18:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_uniqueindexdemo_performanceoptimizedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmanagedDemo',
            fields=[
                ('view_id', models.IntegerField(primary_key=True, serialize=False)),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_table', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unmanaged Demo View',
                'db_table': 'calculation_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLabelDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'App Label Demo',
            },
        ),
        migrations.CreateModel(
            name='CategoryDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Category Demos',
                'default_related_name': '%(app_label)s_%(model_name)s_items',
            },
        ),
        migrations.CreateModel(
            name='CustomTableDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Custom Table Demo',
                'verbose_name_plural': 'Custom Table Demos',
                'db_table': 'custom_content_table',
                'db_table_comment': 'Custom table for storing content with specific naming',
            },
        ),
        migrations.CreateModel(
            name='DBFeaturesDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'DB Features Demo',
                'required_db_features': ['supports_json_field'],
            },
        ),
        migrations.CreateModel(
            name='DBVendorDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonb_data', models.JSONField()),
                ('array_data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'PostgreSQL Specific Demo',
                'required_db_vendor': 'postgresql',
            },
        ),
        migrations.CreateModel(
            name='LatestByDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('priority', models.IntegerField(default=1)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date'],
                'get_latest_by': 'published_date',
            },
        ),
        migrations.CreateModel(
            name='ManagerDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Manager Demo',
                'verbose_name_plural': 'Manager Demos',
                'ordering': ['-published_at'],
                'base_manager_name': 'objects',
                'default_manager_name': 'published',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MultiLatestByDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField()),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'get_latest_by': ['-priority', 'published_date'],
            },
        ),
        migrations.CreateModel(
            name='NoPermissionsDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PermissionsDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('classification_level', models.CharField(choices=[('public', 'Public'), ('confidential', 'Confidential'), ('secret', 'Secret'), ('top_secret', 'Top Secret')], max_length=20)),
            ],
            options={
                'permissions': [('can_view_confidential', 'Can view confidential documents'), ('can_view_secret', 'Can view secret documents'), ('can_view_top_secret', 'Can view top secret documents'), ('can_declassify', 'Can declassify documents'), ('can_export', 'Can export documents')],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ProxyBaseDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectOnSaveDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='TablespaceDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_data', models.TextField()),
                ('binary_data', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Tablespace Demo',
                'db_tablespace': 'large_data_space',
            },
        ),
        migrations.CreateModel(
            name='CategoryItemDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorydemo')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveProxyDemo',
            fields=[
            ],
            options={
                'verbose_name': 'Active Person Demo',
                'verbose_name_plural': 'Active Person Demos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.proxybasedemo',),
        ),
        migrations.CreateModel(
            name='UniqueTogetherDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('shift_date', models.DateField()),
            ],
            options={
                'unique_together': {('driver', 'restaurant'), ('driver', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveMetaDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorydemo')),
            ],
            options={
                'verbose_name': 'Comprehensive Meta Demo',
                'verbose_name_plural': 'Comprehensive Meta Demos',
                'db_table': 'comprehensive_meta_demo',
                'db_table_comment': 'Comprehensive demonstration of Django Meta options',
                'ordering': ['-published_at', '-created_at', 'title'],
                'permissions': [('can_feature_meta', 'Can feature meta content'), ('can_publish_meta', 'Can publish meta content'), ('can_moderate_meta', 'Can moderate meta content'), ('can_view_meta_analytics', 'Can view meta analytics')],
                'get_latest_by': ['published_at', '-created_at'],
                'default_related_name': 'meta_%(class)s_set',
                'indexes': [models.Index(fields=['status', '-published_at'], name='meta_status_pub_idx'), models.Index(fields=['author', '-created_at'], name='meta_author_created_idx'), models.Index(fields=['category', 'status'], name='meta_cat_status_idx'), models.Index(fields=['-view_count'], name='meta_popular_idx'), models.Index(fields=['slug'], name='meta_slug_idx'), models.Index(condition=models.Q(('status', 'published')), fields=['-published_at'], name='meta_published_date_idx'), models.Index(condition=models.Q(('rating__gte', 4.0), ('status', 'published')), fields=['rating'], name='meta_high_rated_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'category'), name='meta_unique_slug_per_category'), models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='meta_valid_rating_range'), models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='meta_positive_view_count')],
            },
        ),
        migrations.CreateModel(
            name='AnswerDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questiondemo')),
            ],
            options={
                'order_with_respect_to': 'question',
            },
        ),
    ]
