# Generated by Django 5.2.5 on 2025-08-20 01:09

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['status'], name='indexes_pra_status_0a74d9_idx'), models.Index(fields=['category'], name='indexes_pra_categor_481776_idx'), models.Index(fields=['created_at'], name='indexes_pra_created_0c574d_idx'), models.Index(fields=['status', 'category'], name='indexes_pra_status_abc114_idx'), models.Index(fields=['category', '-created_at'], name='indexes_pra_categor_3b88b8_idx'), models.Index(fields=['status', '-published_at', 'is_featured'], name='indexes_pra_status_0132cf_idx'), models.Index(condition=models.Q(('status', 'published')), fields=['title', 'slug'], name='published_articles_idx'), models.Index(condition=models.Q(('rating__gte', 4.0)), fields=['rating'], name='high_rating_articles_idx'), models.Index(condition=models.Q(('view_count__gt', 1000), ('is_featured', True)), fields=['view_count'], name='popular_featured_articles_idx'), models.Index(models.OrderBy(django.db.models.functions.text.Lower('title'), descending=True), name='lower_title_idx'), models.Index(django.db.models.functions.text.Length('content'), name='content_length_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('view_count'), '*', models.F('rating')), name='popularity_score_idx'), models.Index(fields=['status'], include=('title', 'created_at'), name='status_covering_idx'), models.Index(fields=['category', 'status'], include=('title', 'summary', 'view_count'), name='category_status_covering_idx'), models.Index(django.db.models.functions.text.Upper('category'), django.db.models.functions.comparison.Coalesce('published_at', 'created_at'), name='category_publish_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='rating_range'), models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='view_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('customer_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_purchase', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-lifetime_value', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['is_active'], name='indexes_pra_is_acti_91b650_idx'), models.Index(fields=['customer_tier'], name='indexes_pra_custome_529742_idx'), models.Index(fields=['is_vip'], name='indexes_pra_is_vip_4db762_idx'), models.Index(fields=['country', 'city'], name='indexes_pra_country_46d944_idx'), models.Index(fields=['postal_code'], name='indexes_pra_postal__f8688e_idx'), models.Index(fields=['-date_joined'], name='indexes_pra_date_jo_e614e9_idx'), models.Index(fields=['-last_purchase'], name='indexes_pra_last_pu_791135_idx'), models.Index(fields=['-total_spent'], name='indexes_pra_total_s_5485d0_idx'), models.Index(fields=['-lifetime_value'], name='indexes_pra_lifetim_ae6e16_idx'), models.Index(fields=['-total_orders'], name='indexes_pra_total_o_84c3e6_idx'), models.Index(fields=['customer_tier', '-total_spent'], name='indexes_pra_custome_86cf0d_idx'), models.Index(fields=['country', 'customer_tier'], name='indexes_pra_country_b9158e_idx'), models.Index(condition=models.Q(('is_active', True)), fields=['total_spent', 'total_orders'], name='active_customers_analytics'), models.Index(condition=models.Q(('total_orders__gte', 5)), fields=['last_purchase'], name='repeat_customers_idx'), models.Index(condition=models.Q(('lifetime_value__gte', 1000000)), fields=['lifetime_value'], name='high_value_customers_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('total_spent'), '/', models.F('total_orders')), condition=models.Q(('total_orders__gt', 0)), name='average_order_value_idx'), models.Index(fields=['country'], include=('customer_tier', 'total_spent', 'total_orders'), name='country_analytics_cover_idx'), models.Index(fields=['customer_tier'], include=('first_name', 'last_name', 'email', 'total_spent'), name='tier_customer_cover_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level'], name='indexes_pra_level_a57b00_idx'), models.Index(fields=['-timestamp'], name='indexes_pra_timesta_61c8a8_idx'), models.Index(fields=['module'], name='indexes_pra_module_4a82b1_idx'), models.Index(fields=['user_id'], name='indexes_pra_user_id_25c5bc_idx'), models.Index(fields=['duration_ms'], name='indexes_pra_duratio_41515b_idx'), models.Index(fields=['request_path'], name='indexes_pra_request_ed8644_idx'), models.Index(fields=['timestamp', 'level'], name='indexes_pra_timesta_52f3aa_idx'), models.Index(fields=['-timestamp', 'module'], name='indexes_pra_timesta_6cbf09_idx'), models.Index(fields=['module', 'function'], name='indexes_pra_module_050d76_idx'), models.Index(fields=['ip_address', '-timestamp'], name='indexes_pra_ip_addr_e6f68d_idx'), models.Index(condition=models.Q(('level__in', ['error', 'critical'])), fields=['-timestamp'], name='error_logs_idx'), models.Index(condition=models.Q(('level', 'error')), fields=['module', 'function'], name='error_source_idx'), models.Index(condition=models.Q(('level__in', ['warning', 'error', 'critical'])), fields=['user_id', '-timestamp'], name='user_issues_idx'), models.Index(condition=models.Q(('duration_ms__gte', 1000)), fields=['duration_ms'], name='slow_requests_idx'), models.Index(django.db.models.functions.text.Length('message'), name='message_length_idx'), models.Index(fields=['level'], include=('timestamp', 'module', 'message'), name='log_dashboard_cover_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sales_count', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='indexes_pra_is_acti_47a1db_idx'), models.Index(fields=['category'], name='indexes_pra_categor_a6be34_idx'), models.Index(fields=['brand'], name='indexes_pra_brand_b1ddbf_idx'), models.Index(fields=['price'], name='indexes_pra_price_41bbb2_idx'), models.Index(fields=['stock_quantity'], name='indexes_pra_stock_q_ebed55_idx'), models.Index(fields=['sales_count'], name='indexes_pra_sales_c_86e60f_idx'), models.Index(fields=['category', 'subcategory'], name='indexes_pra_categor_2ad312_idx'), models.Index(fields=['is_active', 'category', '-price'], name='indexes_pra_is_acti_71266b_idx'), models.Index(fields=['brand', 'category', '-created_at'], name='indexes_pra_brand_bb6261_idx'), models.Index(condition=models.Q(('is_active', True), ('stock_quantity__gt', 0)), fields=['price', 'stock_quantity'], name='available_products_idx'), models.Index(condition=models.Q(('discount_percentage__gt', 0), ('is_active', True)), fields=['discount_percentage'], name='discounted_products_idx'), models.Index(condition=models.Q(('sales_count__gte', 100)), fields=['sales_count'], name='bestseller_products_idx'), models.Index(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('price'), '*', django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('discount_percentage'))), '/', models.Value(100)), name='final_price_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('price'), '-', models.F('cost')), name='profit_margin_idx'), models.Index(fields=['category'], include=('name', 'price', 'stock_quantity'), name='category_details_cover_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_method', models.CharField(blank=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='indexes_practice.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='indexes_pra_status_1b5d72_idx'), models.Index(fields=['customer', 'status'], name='indexes_pra_custome_8699b4_idx'), models.Index(fields=['-created_at'], name='indexes_pra_created_dae7de_idx'), models.Index(fields=['order_number'], name='indexes_pra_order_n_0b551b_idx'), models.Index(fields=['-total_amount'], name='indexes_pra_total_a_aaa1e0_idx'), models.Index(fields=['created_at', 'total_amount'], name='indexes_pra_created_802631_idx'), models.Index(fields=['status', '-total_amount'], name='indexes_pra_status_877e7c_idx'), models.Index(fields=['shipping_method'], name='indexes_pra_shippin_97561a_idx'), models.Index(fields=['tracking_number'], name='indexes_pra_trackin_ddeea1_idx'), models.Index(fields=['shipped_at'], name='indexes_pra_shipped_fb8ed7_idx'), models.Index(fields=['delivered_at'], name='indexes_pra_deliver_451635_idx'), models.Index(fields=['created_at', 'status'], name='indexes_pra_created_1c04bb_idx'), models.Index(fields=['-created_at', 'customer'], name='indexes_pra_created_775a08_idx'), models.Index(fields=['customer', '-created_at'], name='indexes_pra_custome_5b5bc2_idx'), models.Index(fields=['status', 'shipping_method'], name='indexes_pra_status_d792cd_idx'), models.Index(condition=models.Q(('status__in', ['pending', 'processing', 'shipped'])), fields=['created_at', 'total_amount'], name='active_orders_idx'), models.Index(condition=models.Q(('status', 'delivered')), fields=['customer', 'total_amount'], name='completed_orders_cust_idx'), models.Index(condition=models.Q(('status__in', ['shipped', 'delivered']), models.Q(('tracking_number', ''), _negated=True)), fields=['tracking_number'], name='tracked_orders_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('total_amount'), '/', models.F('items_count')), condition=models.Q(('items_count__gt', 0)), name='average_item_price_idx'), models.Index(django.db.models.expressions.CombinedExpression(models.F('tax_amount'), '+', models.F('shipping_cost')), name='additional_costs_idx'), models.Index(fields=['status'], include=('total_amount', 'created_at', 'items_count'), name='status_summary_cover_idx'), models.Index(fields=['customer'], include=('order_number', 'total_amount', 'status', 'created_at'), name='customer_orders_cover_idx')],
            },
        ),
    ]
